In [8]:
using Polyhedra

In [9]:
h = SimpleHRepresentation(eye(2), zeros(2))

H-representation
begin
 2 3 real
 0.0 -1.0 -0.0
 0.0 -0.0 -1.0
end

In [3]:
supertype(typeof(h))

Polyhedra.HRepresentation{2,Float64}

In [4]:
typeof(h)

Polyhedra.SimpleHRepresentation{2,Float64}

In [5]:
using StaticArrays

In [7]:
struct Foo{T}
    position::SVector{2, T}
    velocity::SVector{2, T}
end

In [8]:
data = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [9]:
reinterpret(Foo{Int}, data)

1-element Array{Foo{Int64},1}:
 Foo{Int64}([1, 2], [3, 4])

In [10]:
using JuMP

In [11]:
m = Model()
@variable m x[1:4]

4-element Array{JuMP.Variable,1}:
 x[1]
 x[2]
 x[3]
 x[4]

In [14]:
reinterpret(Ref{Foo{eltype(x)}}, x)

LoadError: argument is an abstract type; size is indeterminate

In [39]:
include("boxatlas.jl")

Box

In [40]:
p = Box.from_bounds([-1, -1], [1, 1])

H-representation
begin
 4 3 real
 1.0 -1.0 -0.0
 1.0 -0.0 -1.0
 1.0 1.0 0.0
 1.0 0.0 1.0
end

In [41]:
h = collect(Box.HRepIter(p))[1]

Polyhedra.HalfSpace{2,Float64}([1.0, 0.0], 1.0)

In [44]:
h.a' * [0, 0] <= h.β

true

In [15]:
state = starthrep(p)
while !donehrep(p, state)
    (h, state) = nexthrep(p, state)
    @show h
end

h = Polyhedra.HalfSpace{2,Float64}([1.0, 0.0], -1.0)
h = Polyhedra.HalfSpace{2,Float64}([0.0, 1.0], -1.0)
h = Polyhedra.HalfSpace{2,Float64}([-1.0, -0.0], -1.0)
h = Polyhedra.HalfSpace{2,Float64}([-0.0, -1.0], -1.0)
