In [1]:
using Revise

In [3]:
using Plots; gr()

Plots.GRBackend()

In [189]:
import Nets2
reload("Nets2")

In [190]:
xs = linspace(-pi, pi, 20)
f = x -> sin(x)
ys = f.(xs)

20-element Array{Float64,1}:
 -1.22465e-16
 -0.324699   
 -0.614213   
 -0.837166   
 -0.9694     
 -0.996584   
 -0.915773   
 -0.735724   
 -0.475947   
 -0.164595   
  0.164595   
  0.475947   
  0.735724   
  0.915773   
  0.996584   
  0.9694     
  0.837166   
  0.614213   
  0.324699   
  1.22465e-16

In [236]:
net = Nets2.Chain(
    Nets2.Affine(10, 1),
    Nets2.activation(Nets2.elu),
    Nets2.Affine(10, 10),
    Nets2.activation(Nets2.elu),
    Nets2.Affine(1, 10),
    Nets2.activation(Nets2.elu)
)
Nets2.initialize!(() -> 0.1 * randn(), net)

In [237]:
xx = linspace(-pi, pi, 100)
yy = f.(xx)
yhat = net.(xx)
plt = plot(xx, yy)
plot!(plt, xx, first.(yhat))
plot!(plt, xs, ys, line=nothing, marker=:dot)
plt

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
<polyline clip-path="url(#clip2602)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 54.4598,193.812 59.6167,204.703 64.7737,215.551 69.9306,226.311 75.0876,236.94 80.2446,247.395 85.4015,257.634 90.5585,267.617 95.7154,277.302 100.872,286.652 
 106.029,295.627 111.186,304.192 116.343,312.313 121.5,319.957 126.657,327.093 131.814,333.692 136.971,339.728 142.128,345.176 147.285,350.015 152.442,354.225 
 157.599,357.789 162.756,360.693 167.913,362.924 173.07,364.475 178.227,365.339 183.384,365.511 188.541,364.993 193.698,363.785 198.855,361.893 204.012,359.324 
 209.169,356.089 214.326,352.2 219.482,347.673 224.639,342.527 229.796,336.782 234.953,330.461 240.11,323.59 245.267,316.197 250.424,308.31 255.581,299.963 
 260.738,291.188 265.895,282.021 271.052,272.499 276.209,262.66 281.366,252.544 286.523,242.192 291.68,231.644 296.837,220.944 301.994,210.135 307.151,199.261 
 312.308,188.364 317.465,177.489 322.622,166.68 327.779,155.98 332.936,145.433 338.093,135.08 343.25,124.964 348.406,115.125 353.563,105.603 358.72,96.4362 
 363.877,87.6614 369.034,79.3141 374.191,71.4278 379.348,64.0343 384.505,57.1633 389.662,50.8426 394.819,45.0976 399.976,39.9514 405.133,35.4248 410.29,31.5359 
 415.447,28.3004 420.604,25.7314 425.761,23.8392 430.918,22.6315 436.075,22.113 441.232,22.2859 446.389,23.1494 451.546,24.7002 456.703,26.9319 461.86,29.8356 
 467.017,33.3996 472.174,37.6094 477.33,42.4483 482.487,47.8966 487.644,53.9325 492.801,60.5317 497.958,67.6675 503.115,75.3113 508.272,83.4322 513.429,91.9976 
 518.586,100.973 523.743,110.322 528.9,120.007 534.057,129.99 539.214,140.23 544.371,150.685 549.528,161.314 554.685,172.074 559.842,182.921 564.999,193.812 
 
 "/>
<polyline clip-path="url(#clip2602)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 54.4598,180.36 59.6167,180.367 64.7737,180.374 69.9306,180.38 75.0876,180.388 80.2446,180.395 85.4015,180.402 90.5585,180.41 95.7154,180.417 100.872,180.425 
 106.029,180.433 111.186,180.441 116.343,180.449 121.5,180.458 126.657,180.466 131.814,180.475 136.971,180.484 142.128,180.493 147.285,180.503 152.442,180.512 
 157.599,180.522 162.756,180.531 167.913,180.541 173.07,180.552 178.227,180.562 183.384,180.573 188.541,180.584 193.698,180.595 198.855,180.606 204.012,180.618 
 209.169,180.63 214.326,180.641 219.482,180.654 224.639,180.666 229.796,180.678 234.953,180.691 240.11,180.704 245.267,180.717 250.424,180.73 255.581,180.744 
 260.738,180.757 265.895,180.771 271.052,180.785 276.209,180.799 281.366,180.814 286.523,180.828 291.68,180.843 296.837,180.858 301.994,180.873 307.151,180.888 
 312.308,180.903 317.465,180.917 322.622,180.932 327.779,180.947 332.936,180.961 338.093,180.976 343.25,180.991 348.406,181.005 353.563,181.02 358.72,181.034 
 363.877,181.049 369.034,181.063 374.191,181.078 379.348,181.092 384.505,181.106 389.662,181.121 394.819,181.135 399.976,181.149 405.133,181.163 410.29,181.177 
 415.447,181.19 420.604,181.204 425.761,181.218 430.918,181.231 436.075,181.245 441.232,181.259 446.389,181.272 451.546,181.286 456.703,181.299 461.86,181.313 
 467.017,181.326 472.174,181.34 477.33,181.353 482.487,181.367 487.644,181.38 492.801,181.393 497.958,181.406 503.115,181.42 508.272,181.433 513.429,181.446 
 518.586,181.459 523.743,181.472 528.9,181.484 534.057,181.497 539.214,181.51 544.371,181.523 549.528,181.535 554.685,181.548 559.842,181.561 564.999,181.573 
 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 y2 
 
 
 
 
 
 y3

In [238]:
batches = [zip(xs, ys)]

1-element Array{Base.Iterators.Zip2{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1}},1}:
 Base.Iterators.Zip2{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1}}(-3.141592653589793:0.3306939635357677:3.141592653589793, [-1.22465e-16, -0.324699, -0.614213, -0.837166, -0.9694, -0.996584, -0.915773, -0.735724, -0.475947, -0.164595, 0.164595, 0.475947, 0.735724, 0.915773, 0.996584, 0.9694, 0.837166, 0.614213, 0.324699, 1.22465e-16])

In [239]:
loss = (params, batch) -> begin
    n = Nets2.with_params(net, params)
    sum((xy) -> sum(abs2, n(xy[1]) .- xy[2]), batch)
end

(::#206) (generic function with 1 method)

In [243]:
param_vector = CatView(Nets2.params(net))
for i in 1:1000
    for batch in batches
        ∇ = ReverseDiff.gradient(params -> loss(params, batch), param_vector)
        param_vector .-= 0.01 .* ∇
    end
end

In [244]:
yhat = net.(xx)
plt = plot(xx, yy)
plot!(plt, xx, first.(yhat))
plt

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
<polyline clip-path="url(#clip3002)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.1436,205.857 44.61,216.638 50.0763,227.375 55.5427,238.026 61.0091,248.547 66.4755,258.896 71.9419,269.031 77.4082,278.913 82.8746,288.5 88.341,297.754 
 93.8074,306.638 99.2737,315.117 104.74,323.155 110.206,330.721 115.673,337.785 121.139,344.317 126.606,350.292 132.072,355.685 137.538,360.474 143.005,364.641 
 148.471,368.169 153.938,371.043 159.404,373.253 164.87,374.788 170.337,375.642 175.803,375.813 181.269,375.3 186.736,374.105 192.202,372.232 197.669,369.689 
 203.135,366.486 208.601,362.637 214.068,358.156 219.534,353.062 225,347.375 230.467,341.119 235.933,334.318 241.4,326.999 246.866,319.193 252.332,310.93 
 257.799,302.245 263.265,293.171 268.731,283.745 274.198,274.006 279.664,263.993 285.131,253.745 290.597,243.305 296.063,232.714 301.53,222.014 306.996,211.25 
 312.462,200.464 317.929,189.7 323.395,179 328.862,168.409 334.328,157.969 339.794,147.721 345.261,137.708 350.727,127.969 356.193,118.543 361.66,109.469 
 367.126,100.784 372.593,92.5211 378.059,84.7148 383.525,77.3964 388.992,70.5952 394.458,64.3386 399.925,58.6519 405.391,53.558 410.857,49.0773 416.324,45.2279 
 421.79,42.0253 427.256,39.4823 432.723,37.6094 438.189,36.4138 443.656,35.9006 449.122,36.0718 454.588,36.9266 460.055,38.4616 465.521,40.6706 470.987,43.5448 
 476.454,47.0726 481.92,51.2398 487.387,56.0295 492.853,61.4226 498.319,67.3972 503.786,73.9294 509.252,80.9927 514.718,88.5589 520.185,96.5974 525.651,105.076 
 531.118,113.96 536.584,123.214 542.05,132.801 547.517,142.683 552.983,152.818 558.449,163.167 563.916,173.689 569.382,184.339 574.849,195.076 580.315,205.857 
 
 "/>
<polyline clip-path="url(#clip3002)" style="stroke:#e26f46; stroke-width:1; stroke-opacity:1; fill:none" points="
 39.1436,251.581 44.61,260.682 50.0763,269.039 55.5427,276.711 61.0091,283.753 66.4755,290.215 71.9419,296.143 77.4082,301.579 82.8746,306.561 88.341,311.125 
 93.8074,315.302 99.2737,319.123 104.74,322.612 110.206,325.796 115.673,328.696 121.139,331.331 126.606,333.719 132.072,335.876 137.538,337.816 143.005,339.551 
 148.471,341.092 153.938,342.445 159.404,343.618 164.87,344.616 170.337,345.44 175.803,346.091 181.269,346.564 186.736,346.854 192.202,346.951 197.669,346.84 
 203.135,346.498 208.601,345.898 214.068,345.002 219.534,343.756 225,342.069 230.467,339.664 235.933,336.356 241.4,332.154 246.866,327.086 252.332,321.161 
 257.799,314.486 263.265,307.004 268.731,298.647 274.198,289.345 279.664,279.101 285.131,267.873 290.597,255.595 296.063,242.197 301.53,227.602 306.996,211.725 
 312.462,194.84 317.929,178.141 323.395,161.71 328.862,145.529 334.328,129.578 339.794,114.062 345.261,99.7516 350.727,86.6952 356.193,74.8437 361.66,64.1488 
 367.126,54.5634 372.593,46.0421 378.059,38.541 383.525,32.0181 388.992,26.4331 394.458,21.7559 399.925,17.9885 405.391,15.1125 410.857,13.1443 416.324,12.0543 
 421.79,11.811 427.256,12.372 432.723,13.5541 438.189,15.1924 443.656,17.2508 449.122,19.6986 454.588,22.5073 460.055,25.65 465.521,29.1028 470.987,32.8429 
 476.454,36.8484 481.92,41.0985 487.387,45.5739 492.853,50.2562 498.319,55.1284 503.786,60.1741 509.252,65.3783 514.718,70.7266 520.185,76.2058 525.651,81.8031 
 531.118,87.5066 536.584,93.305 542.05,99.1878 547.517,105.145 552.983,111.166 558.449,117.243 563.916,123.368 569.382,129.53 574.849,135.724 580.315,141.941 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [246]:
param_vector

141-element CatViews.CatView{6,Float64}:
  0.314799  
  0.0493019 
  0.561192  
  0.711589  
  0.313391  
 -1.04097   
 -1.27727   
  0.0658407 
  0.0139828 
 -0.0703404 
 -0.40991   
 -0.105425  
 -0.77582   
  ⋮         
 -0.524718  
  0.00384847
  0.372765  
 -0.0119575 
  0.0727551 
  0.701289  
  0.392373  
  0.328673  
  0.360447  
  0.59701   
  0.852871  
 -0.368602  

In [245]:
ReverseDiff.gradient(params -> loss(params, batch), param_vector)

141-element Array{Float64,1}:
 -1.13765   
 -1.89267e-5
 -2.38438   
 -3.08864   
 -1.21771   
 -0.907063  
  0.449463  
 -0.0217478 
 -0.180902  
  0.0549902 
 -0.651718  
 -0.132547  
 -1.26654   
  ⋮         
  0.424123  
 -0.0777788 
  1.55742   
 -0.036854  
  0.0924701 
  4.17959   
  2.26533   
  1.60159   
  1.37286   
  3.50048   
 -4.20599   
  3.11689   

In [181]:
loss = (param_vector, x, y) -> begin
    params, s, e = splitview(param_vector, param_sizes...)
    n = Nets2.with_params(net, params...)
    ŷ = n(x)
    sum(abs2, ŷ .- y)
end

function update!(loss, net, batches)
    param_sizes = size.(Nets2.params(net))
    function inner(param_vector, x, y)
        params, s, e = splitview(param_vector, param_sizes...)
        n = Nets2.with_params(net, params...)
        ŷ = n(x)
        loss(ŷ, y)
    end
    param_vector = CatView(Nets2.params(net)...)
    ∇ = zeros(size(param_vector))
    grad_result = similar(∇)
    for batch in batches
        ∇ .= 0
        for (x, y) in batch
            ReverseDiff.gradient!(grad_result, params -> inner(params, x, y), param_vector)
            ∇ .+= grad_result ./ length(batch)
        end
    end
    ∇
end
    

update! (generic function with 1 method)

In [184]:
param_vector = CatView(Nets2.params(net)...)
for i in 1:100
    ∇ = update!(loss, net, batches)
    param_vector .-= 0.1 .* ∇
end

In [186]:
update!(loss, net, batches)

31-element Array{Float64,1}:
 -0.00248287 
 -0.000319703
  0.00156972 
  0.000656617
 -0.000565252
 -0.000204491
  0.000226818
 -0.000722073
 -0.00507269 
 -4.57776e-5 
 -0.00123884 
  8.47473e-7 
 -0.000770405
  ⋮          
  0.000219476
  0.000470093
  0.000356932
  0.000676513
  0.00166739 
 -0.00419664 
  0.000179729
  0.000551915
 -0.00391531 
  0.000260779
  0.000404994
  0.000419991

In [81]:
loss = Nets2.sample_loss(net) do x, y
    sum(abs2, x .- y)
end

(::#5) (generic function with 1 method)

In [83]:
loss(Nets2.FlatParams(net), [0.0], [0.0])

0.929818787910725

In [84]:
import Nets

In [ ]:
options = Nets.AdamOpts(batch_size = length(first(batches)))
flat = Nets2.FlatParams(net)
optimizer = Nets.AdamOptimizer(options, 
    Nets.StochasticOptimization.Adam(Float64)
    ∇ = zeros(flat.flat)
    

In [27]:
batch = first(batches)
loss2(Nets2.params(net))

246.15923873699808

In [29]:
sum(loss1(Nets2.params(net), x, y) for (x, y) in batch)

246.15923873699808

In [30]:
using CatViews

LoadError: ArgumentError: Module CatViews not found in current path.
Run `Pkg.add("CatViews")` to install the CatViews package.